### PR TITLE
Change NineAnime domain

### PR DESCRIPTION
**Pull request by JugaramZa**
Changed to mirror domain of 9anime.to . the changed domain info is taken from 9anime.me site as we know 9anime.me is hub of offical 9anime domains.
The reason of change to mirror domain is to prevent from isp blocking .using vpn may be a solution but it consumes more battery in background. and dns doesnt work with cellular data .
Hope you understood the reason .
Please checkout the 9anime.me website to verify the changed domain is official or not before merging pull request.

### CODE REVIEW

**Comment by minhh2792** [comment]
This is so unnecessary

**Comment by JugaramZa** [comment]
> This is so unnecessary

By changing to mirror domain majority of the users from different areas can use this parser without any issues like isp blocking.While the .to domain doesnt work in most of the regions for the users.The another reason for this pull requests is also for better user experience.This pull requests also helps users to avoid using any vpn & dns and directly play the content and enjoy.

**Comment by brahmkshatriya** [comment]
@enimax-anime pls verify

**Comment by enimax-anime** [comment]
All 9anime websites have WAF enabled, so I can't verify if `.me` would work or not, unfortunately :(

**Comment by brahmkshatriya** [comment]
> All 9anime websites have WAF enabled, so I can't verify if `.me` would work or not, unfortunately :(

they changed 9anime.to to 9anime.ph, I hope your service's isp doesnt block 9anime.ph

**Comment by enimax-anime** [comment]
Oh, I meant `.ph` not `.me` lol. But yeah, they all have WAF enabled, atleast they do for me. Not sure if that's the case for everyone or not.

**Pull request merged**
