### PR TITLE
Fix Anilist API

### PR DESCRIPTION
**Pull request by hoangvu12**
Fix Anilist API by adding Referer header to trick their system into that the requests are coming from the main website.

Tested on my device, I don't know if it works on other devices but it should.

This is a temporary fix anyway, eventually, the app will work without this fix when Anilist fixed their server.

### CODE REVIEW

**Comment by scrazzz** [comment]
First of all, `referer` should always end with a slash (`/`). So it should be `https://anilist.co/`.

Secondly, `nicehttp` needs to be updated to version 0.4.0.

I'd like to note that Saikou works for me on the latest beta version: 1.2.0.23.
I have no issues with AniList anymore.

**Comment by hoangvu12** [comment]
Fixed those issues!

**Comment by scrazzz** [comment]
I don't think adding referer would "trick" their system to think that the requests are coming from the website. Are you sure adding this actually fixes it?

**Comment by hoangvu12** [comment]
> I don't think adding referer would "trick" their system to thinking that the requests are coming from the website. Are you sure adding this actually fixes it?

Maybe, because it only rate limits my requests when referer header is not their domain. Maybe try to add user-agent and other headers to *trick* them?

**Comment by brahmkshatriya** [comment]
No this doesnt fix the issue at the hand, I would rather only use the recommended way of how anilist's doc recommends it

**Pull request closed without merging**
