### PR TITLE
Update domain url

### PR DESCRIPTION
**Pull request by givemyusd**
to prevent from isp block

### CODE REVIEW

**Comment by scrazzz** [comment]
Can you verify that these TLDs are the original one or a clone? Also, why not just use a VPN or change DNS in Settings > Common > Selected DNS.

**Comment by Adolar0042** [comment]
can confirm they're original, the gogo one is just the latest one that the one we use right now just redirects to and the 9anime one is a mirror (see https://9anime.me)
Though I don't see any point in changing them, due to the ways to get around it you mentioned already

**Comment by givemyusd** [comment]
> Can you verify that these TLDs are the original one or a clone? Also, why not just use a VPN or change DNS in Settings > Common > Selected DNS.

dns mostly doesn't work with cellular data in use
and sites are original ones

**Comment by scrazzz** [comment]
Alright, Thanks.

**Review by scrazzz — APPROVED** [review]

**Pull request merged**
