### PR TITLE
fix grammatical issues

### PR DESCRIPTION
**Pull request by 404-Program-not-found**

### CODE REVIEW

**Comment by brahmkshatriya** [comment]
Rejected

**Comment by 404-Program-not-found** [comment]
is there any specific reason for this decision?

**Comment by brahmkshatriya** [comment]
- You removed intentional capitalisation 
- Some strings were made worse (ex: is your internet suck?)
- also looks to me like pr farming

**Comment by 404-Program-not-found** [comment]
oh crap, I thought that said "stuck", my bad.
I was also not aware of the intentional capitalisation, I can fix that if you want. However, given my 550 commits and 45 pull requests within the past year alone, I am genuinely not looking to pr farm

**Comment by brahmkshatriya** [comment]
Well I'll just fix some stuff on my own then
Thanks for pointing out some mistakes

**Comment by 404-Program-not-found** [comment]
that's all good too 😀, Good luck with future developments!

**Pull request closed without merging**
