### PR TITLE
Switch from Consumet for 9anime

### PR DESCRIPTION
**Pull request by enimax-anime**
Consumet will shut down in a few months, so will the 9anime API route. But, I still plan on hosting the API on my server, so I switched the URLs to not use Consumet anymore.

### CODE REVIEW

**Comment by scrazzz** [comment]
Looks like there was a Type Error:
```
file:///home/runner/work/saikou/saikou/app/src/main/java/ani/saikou/parsers/anime/NineAnime.kt:81:38 Type mismatch: inferred type is String? but String was expected
```

If you can't fix it within this branch then you can close this PR.

**Comment by enimax-anime** [comment]
There we go. I actually tested the changes I made this time, haha. I am not that familiar with Kotlin, so hopefully I didn't write shit code.

**Review by scrazzz — APPROVED** [review]

**Comment by scrazzz** [comment]
Thanks

**Comment by brahmkshatriya** [comment]
Arigato , 🙏

**Pull request merged**
