### PR TITLE
Change zoro to aniwatch

### PR DESCRIPTION
**Pull request by Ash69123**
as the title says

### CODE REVIEW

**Comment by scrazzz** [comment]
It's better to just rename the entire Zoro parser to Aniwatch instead of this half "fix"

**Comment by scrazzz** [comment]
It's not Aniwatch, it's Kaido.
image

**Comment by Ash69123** [comment]
where did kaido come from 
i thought they renamed zoro to aniwatch?

**Comment by scrazzz** [comment]
Superseded by https://github.com/saikou-app/saikou/pull/750

**Pull request closed without merging**
