### PR TITLE
Fix streamsb

### PR DESCRIPTION
**Pull request by jerry08**

### CODE REVIEW

**Comment by scrazzz** [comment]
Looks like `nicehttp` needs to be updated.

**Comment by scrazzz** [comment]
Could you update to version `0.4.2` in this file here: https://github.com/saikou-app/saikou/blob/main/app/build.gradle#L57 ?

Fixes #481 ~~trying to link the issue~~.

**Comment by jerry08** [comment]
All done

**Comment by scrazzz** [comment]
Bruh why's it failing.

**Comment by Adolar0042** [comment]
> Could not resolve com.github.Blatzar:NiceHttp:0.4.2.

**Comment by scrazzz** [comment]
Well yes, I saw the error. The latest version *is* 0.4.2. Not sure what's wrong.

Anyways I'll merge this now.

**Comment by Adolar0042** [comment]
Not sure if this is related, but when looking the repo up on its host it throws an error

image

image

**Pull request merged**
