### PR TITLE
Update FAQactivity

### PR DESCRIPTION
**Pull request by SunglassJerry**
SaikouS is reaal

### CODE REVIEW

**Comment by scrazzz** [comment]
Seems unnecessary + it's not complete yet.

**Comment by SunglassJerry** [comment]
We already had this question, this is just an updated answer + I wrote *under development*

Normal English too easy to read moment 🤓

**Comment by scrazzz** [comment]
Cba to argue over GitHub when I have you already blocked on Discord. I'll leave this up to Shivam to decide.

**Comment by brahmkshatriya** [comment]
Change discord to github repo instead

**Pull request merged**
