### PR TITLE
for simple localization

### PR DESCRIPTION
**Pull request by antonydp**
to achieve full localization of the entire app by incorporating an XML file for other languages.

### CODE REVIEW

**Comment by brahmkshatriya** [comment]
is this completed?

**Comment by Sadwhy** [comment]
1 XML file for everything?

**Comment by brahmkshatriya** [comment]
> 1 XML file for everything?

Basically, yea
Just fixes the strings i used which were needed to be translatable

**Comment by Sadwhy** [comment]
> > 1 XML file for everything?
> 
> Basically, yea Just fixes the strings i used which were needed to be translatable

I can see much more potential in this than just translation. Imagine using old English or I can finally change NineAnime to 9anime.

**Comment by brahmkshatriya** [comment]
Yea you can't change NineAnime to 9anime from XML, need to change in AnimeSources.kt

**Pull request merged**
