### PR TITLE
Delete README.md

### PR DESCRIPTION
**Pull request by edgehub-cloud**
This makes this repo look less retarded

### CODE REVIEW

**Comment by Adolar0042** [comment]
Not sure we can merge this, I believe there is a security issue on line 69.

**Comment by edgehub-cloud** [comment]
my next commit might fuck your browser up a bit....

**Comment by brahmkshatriya** [comment]
hmm tbh, I recommend removing the src folder, before merging

**Comment by Blatzar** [comment]
Remove all the other bloat too, who looks at .kt files anyways? Only the apk is required for open source projects 🙏

**Pull request closed without merging**
