### PR TITLE
New 9anime cipher key

### PR DESCRIPTION
**Pull request by riimuru**

### CODE REVIEW

**Comment by Bilnaa** [comment]
can u load videos with that  tho?

**Comment by riimuru** [comment]
@Bilnaa it fixed search + episodes list. but it looks like the decryption algo for the streaming url needs to change.

**Comment by riimuru** [comment]
@Bilnaa You should now be able to load videos 👍

**Comment by brahmkshatriya** [comment]
> @Bilnaa You should now be able to load videos 👍 

Can you send a message in #devs on discord server

**Pull request merged**
