### PR TITLE
[Feature] Discord Rich Presence

### PR DESCRIPTION
**Pull request by teecoding**
## 📢 Description:
📌 This pull request brings the ability to show off to all your friends on Discord what you're currently watching or reading in Saikou! 

## 💡 Added Features:
✨ This pull request introduces the following new features or enhancements:
- Get ready for some seamless communication between Discord Gateway, keeping your Rich Presence updated and shining! 
- Level up your experience with Saikou by logging into Discord directly! 🚀🔑

## 📊 Impact and Benefits:
✅ These changes will result in:
- Enhanced advertisement for Saikou since your rich presence will shine across all Discord servers! 📣✨

## 📸 Screenshots:

<div align="center">

image
image
image

🌟 Thank you for considering this pull request!  🌟
🌟 Your feedback and suggestions are greatly appreciated. 🌟
</div>

### CODE REVIEW

**Comment by Sadwhy** [comment]
Fuck yeah. But looks like it still needs some polishing.

**Comment by ovi293** [comment]
Cool feature. Can you add the same feature to TachiyomiJ2K please? This might help: https://github.com/Jays2Kings/tachiyomiJ2K/issues/1568

**Comment by brahmkshatriya** [comment]
do you intend to finish this?

**Comment by ArjixWasTaken** [comment]
@brahmkshatriya can you provide input on what needs to be finished? I am up for the task

**Comment by brahmkshatriya** [comment]
> @brahmkshatriya can you provide input on what needs to be finished? I am up for the task

I literally have no idea, I think it doesnt work as of now
Might wanna look into what they are trying to do

**Comment by brahmkshatriya** [comment]
Also if possible, I would like it, if the gson dependency was removed and Kotlinx Serialization was used

**Comment by ArjixWasTaken** [comment]
:monkeok:

**Pull request closed without merging**
